replace json config by object config
pmem/pmemkv-nodejs pull request #30
Opened 2019-09-04 08:02 UTC by how759

Use js object as config to pmemkv.db() rather than a json string

2019-09-04 10:20 UTC, lukaszstolarczuk reviewed
it looks good to use config object instead of json string, but is it possible to encapsulate these methods in some other, independent class (like we have in C++) ?

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-:-Lnvm52O7rPGVzivwzny:b-2d4o0e)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @how759)

___
*[lib/database.cc, line 74 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lnvl9nc8Azv5Gjg-Sj_:-Lnvl9nc8Azv5Gjg-Sja:bzabnlz) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L74)):*
> ```cpp
>         Napi::TypeError::New(env, "invalid arguments").ThrowAsJavaScriptException();
>     std::string engine = info[0].As<Napi::String>().Utf8Value();
>     Napi::Object config = info[1].As<Napi::Object>();
> ```

this way we can't pass nullptr as config - can you make it optional so we can still use nulled/empty config
___
*[lib/database.cc, line 85 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjYmM-wf2TB3JdChv:-LnvjYmN2xNjUAEGfrYC:b9yyipa) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L85)):*
> ```cpp
>         Napi::Value key = props.Get(i);
>         Napi::Value value = config.Get(key);
>         if (!key.IsString()){
> ```

this check could be above the config.Get(key);
___
*[lib/database.cc, line 92 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjlsY66y1WnYyREz_:-LnvjlsY66y1WnYyREza:bpelysi) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L92)):*
> ```cpp
>             auto status = cfg.put_string(key.As<Napi::String>().Utf8Value(), value.As<Napi::String>().Utf8Value());
> 	        if (status != pmem::kv::status::OK)
>                 Napi::Error::New(env, "invalid config object").ThrowAsJavaScriptException();
> ```

it's not necessarily an invalid config object, it could just fail to put it to config, couldn't it?
___
*[lib/database.cc, line 97 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvkVEnEcmfo_07dpaQ:-LnvkVEnEcmfo_07dpaR:b-7ropln) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L97)):*
> ```cpp
>             auto status = cfg.put_uint64(key.As<Napi::String>().Utf8Value(), value.As<Napi::Number>().Uint32Value());
>             if (status != pmem::kv::status::OK)
>                 Napi::Error::New(env, "invalid config object").ThrowAsJavaScriptException();
> ```

ditto
___
*[lib/database.cc, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvkHJT5NTX0K-2thW2:-LnvkHJU5UdCGZq7SeB-:b-ybboa7) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L99)):*
> ```cpp
>                 Napi::Error::New(env, "invalid config object").ThrowAsJavaScriptException();
>         }
>         else {
> ```

I guess we could have more then numbers and strings put into config. If you don't feel like implementing them you can just throw "not implemented" exception, because the rest may not be as crucial as the mentioned two, but we may want to implement them later.

anyway, current list of config supported types, is here:
https://github.com/pmem/pmemkv/blob/f36fce69ecec358969d9e5d8629b1a4bfd6a6d3a/doc/libpmemkv_config.3.md
(it's without `double`, which we plan to remove; ref. https://github.com/pmem/pmemkv/pull/408 )
___
*[test/database_spec.js, line 224 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvlifN16WbPanASGYG:-LnvlifN16WbPanASGYH:b-sobz19) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/test/database_spec.js#L224)):*
> ```JavaScript
>             expect(true).to.be.false;
>         } catch (e) {
>             expect(e.message).to.equal('pmemkv_open() failed');
> ```

this may change in near future, but I believe we still want to make config from json possible...?

@igchor, please take a look at this, please


<!-- Sent from Reviewable.io -->

2019-09-05 08:26 UTC, igchor reviewed
@lukasztolarczuk I think it is not needed to have a separate class as long as we can use language provided features. I also think that methods which we expose in C++ like config_put/get should not be exposed in JS. Approach in this PR looks good to me.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-:-Lo-WQdA9SkkVztXU4GX:b-sicv64)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @how759)



<!-- Sent from Reviewable.io -->

2019-09-10 02:37 UTC, how759 commented
___
*[lib/database.cc, line 74 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lnvl9nc8Azv5Gjg-Sj_:-LoO-raF7fWgtgPwEPhw:bksunt4) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this way we can't pass nullptr as config - can you make it optional so we can still use nulled/empty config
</blockquote></details>

Currently pmem::kv::cfg could not be null otherwise the codes below could cause a segmentfault

pmem::kv::config cfg;
kv->open("cmap", std::move(cfg));


<!-- Sent from Reviewable.io -->

2019-09-10 02:51 UTC, how759 commented
___
*[lib/database.cc, line 92 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjlsY66y1WnYyREz_:-LoO1ZCG183EDQTow78g:bof2rsn) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not necessarily an invalid config object, it could just fail to put it to config, couldn't it?
</blockquote></details>

yes, it could just put errormsg() to the Napi::Error. But there is some unexpected output from errormsg(), I intended to solve it in another PR.


<!-- Sent from Reviewable.io -->

2019-09-10 02:55 UTC, how759 commented
___
*[lib/database.cc, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvkHJT5NTX0K-2thW2:-LoO52Cj-uukBuId8-CW:b-s3xqvb) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L99)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess we could have more then numbers and strings put into config. If you don't feel like implementing them you can just throw "not implemented" exception, because the rest may not be as crucial as the mentioned two, but we may want to implement them later.

anyway, current list of config supported types, is here:
https://github.com/pmem/pmemkv/blob/f36fce69ecec358969d9e5d8629b1a4bfd6a6d3a/doc/libpmemkv_config.3.md
(it's without `double`, which we plan to remove; ref. https://github.com/pmem/pmemkv/pull/408 )
</blockquote></details>

Working, will do


<!-- Sent from Reviewable.io -->

2019-09-10 10:31 UTC, how759 commented
___
*[lib/database.cc, line 85 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjYmM-wf2TB3JdChv:-LoPi_ef0o9D6SQ92Kr8:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this check could be above the config.Get(key);
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-10 10:41 UTC, how759 commented
___
*[lib/database.cc, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvkHJT5NTX0K-2thW2:-LoPiwJ77d1US2j5NDUG:bs7wumx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L99)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

Working, will do
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2019-09-10 10:42 UTC, how759 commented
___
*[lib/database.cc, line 92 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjlsY66y1WnYyREz_:-LoPidp7-Bt32xDs0x_T:b-257ipf) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L92)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

yes, it could just put errormsg() to the Napi::Error. But there is some unexpected output from errormsg(), I intended to solve it in another PR.
</blockquote></details>

Please see https://github.com/how759/pmemkv-nodejs/tree/errormsg. It seems that erromsg() does not clear when running the test case


<!-- Sent from Reviewable.io -->

2019-09-16 11:38 UTC, igchor requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 8 unresolved discussions (waiting on @how759 and @lukaszstolarczuk)

___
*[lib/database.cc, line 74 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lnvl9nc8Azv5Gjg-Sj_:-LotpzpV0OFDpmOzcs_g:b-4233ez) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L74)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

Currently pmem::kv::cfg could not be null otherwise the codes below could cause a segmentfault

pmem::kv::config cfg;
kv->open("cmap", std::move(cfg));
</blockquote></details>

This is being tracked here: https://github.com/pmem/pmemkv/issues/415
We plan to just return proper status when config is nullptr
___
*[lib/database.cc, line 92 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjlsY66y1WnYyREz_:-LotqjFM1pVGqaX0kd6Y:b-36gxjj) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L92)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

Please see https://github.com/how759/pmemkv-nodejs/tree/errormsg. It seems that erromsg() does not clear when running the test case
</blockquote></details>

This is fixed by this PR (should be merged soon): https://github.com/pmem/pmemkv/pull/433
___
*[lib/database.cc, line 85 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LotqVuk3Wp70LnOMgXK:-LotqVuk3Wp70LnOMgXL:brabixx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/d750adb5e164b36452e2702f001d951bd96597c3/lib/database.cc#L85)):*
> ```cpp
>         Napi::Value key = props.Get(i);
>         if (!key.IsString()){
>             Napi::Error::New(env, "invalid config object").ThrowAsJavaScriptException();
> ```

I think errormsg could be extended here - maybe "Key should be string" or something like that?
___
*[lib/database.cc, line 100 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LotrB1NBDUy39JURtRH:-LotrB1NBDUy39JURtRI:bdpshmw) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/d750adb5e164b36452e2702f001d951bd96597c3/lib/database.cc#L100)):*
> ```cpp
>         }
>         else {
>             Napi::Error::New(env, "not implemented").ThrowAsJavaScriptException();
> ```

Not necessarly in this PR, but I think it would be good to throw some specialized errors like ErrorNotImplemented (different type for each status from libpmemkv) here. The same is true for other methods (not only constructor).


<!-- Sent from Reviewable.io -->

2019-09-16 13:14 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 5 unresolved discussions (waiting on @how759)

___
*[lib/database.cc, line 74 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lnvl9nc8Azv5Gjg-Sj_:-Lou8vIW8w1hTKfgPpVR:b9fx598) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L74)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This is being tracked here: https://github.com/pmem/pmemkv/issues/415
We plan to just return proper status when config is nullptr
</blockquote></details>

ok, so providing the fix for above mentioned issue will be delivered, it will be ok, I guess.
I'm setting this comment as done
___
*[lib/database.cc, line 92 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjlsY66y1WnYyREz_:-LouAVCg9OlJQ778708p:b229p44) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L92)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This is fixed by this PR (should be merged soon): https://github.com/pmem/pmemkv/pull/433
</blockquote></details>

so, if we merge the above mentioned Igor's fix it will be ok to solve this issue already in here? or you still plan to make another PR ?


<!-- Sent from Reviewable.io -->

2019-09-18 14:31 UTC, lukaszstolarczuk commented
@how759, please rebase with newest changes in this repo and also please take into account pmemkv latest changes, including:
pmem/pmemkv#430

2019-09-23 07:38 UTC, how759 commented
Done rebase





<!-- Sent from Reviewable.io -->

2019-09-23 11:14 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @how759, @igchor, and @lukaszstolarczuk)

___
*[lib/database.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpSoteH2DYfrR_qka8j:-LpSoteIDTkdA0im0KTw:b-pdouw) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/16b4c3e5b042cfbdde72d2c8d8ba8f7923215e66/lib/database.cc#L35)):*
> ```cpp
> #include "database.h"
> #include <string>
> #include <libpmemkv_json_config.h>
> ```

I can't see any usage of this helper library - not in here and neither in an example


<!-- Sent from Reviewable.io -->

2019-09-24 08:28 UTC, how759 commented
___
*[lib/database.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpSoteH2DYfrR_qka8j:-LpXNYuZC-Z9XJAgRF-D:bb6un1j) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/16b4c3e5b042cfbdde72d2c8d8ba8f7923215e66/lib/database.cc#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I can't see any usage of this helper library - not in here and neither in an example
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-09-24 09:10 UTC, igchor reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 5 unresolved discussions (waiting on @how759 and @lukaszstolarczuk)

___
*[lib/database.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpSoteH2DYfrR_qka8j:-LpXWn6h9cLL1UrDOUna:bvievc8) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/16b4c3e5b042cfbdde72d2c8d8ba8f7923215e66/lib/database.cc#L35)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think what Lukasz meant is that we can remove this entirly (header include and linking to it)


<!-- Sent from Reviewable.io -->

2019-09-24 11:22 UTC, how759 commented
___
*[lib/database.cc, line 85 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LotqVuk3Wp70LnOMgXK:-LpY-c6uBrvX8u3Qt4Il:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/d750adb5e164b36452e2702f001d951bd96597c3/lib/database.cc#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think errormsg could be extended here - maybe "Key should be string" or something like that?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-24 11:23 UTC, how759 commented
___
*[lib/database.cc, line 92 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvjlsY66y1WnYyREz_:-LpY-fanB160Hou6V_jB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

so, if we merge the above mentioned Igor's fix it will be ok to solve this issue already in here? or you still plan to make another PR ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-24 11:23 UTC, how759 commented
___
*[lib/database.cc, line 100 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LotrB1NBDUy39JURtRH:-LpY-iBN9oVbbDXSievK:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/d750adb5e164b36452e2702f001d951bd96597c3/lib/database.cc#L100)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Not necessarly in this PR, but I think it would be good to throw some specialized errors like ErrorNotImplemented (different type for each status from libpmemkv) here. The same is true for other methods (not only constructor).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-24 11:26 UTC, how759 commented
___
*[lib/database.cc, line 100 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LotrB1NBDUy39JURtRH:-LpY-rW386bkTztRheO_:bk3usjw) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/d750adb5e164b36452e2702f001d951bd96597c3/lib/database.cc#L100)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

JavaScript do not support catching different type of error, so currently the error is like

try{}
catch(e){
if (e.status == constants.status.NOT_FOUND){}
else if (e.status == constants.status.UNKNOWN_ERROR){}
}


<!-- Sent from Reviewable.io -->

2019-09-24 11:26 UTC, how759 commented
___
*[lib/database.cc, line 35 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpSoteH2DYfrR_qka8j:-LpY0U7N6BIYljIHADfp:bb6un1j) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/16b4c3e5b042cfbdde72d2c8d8ba8f7923215e66/lib/database.cc#L35)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think what Lukasz meant is that we can remove this entirly (header include and linking to it)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-09-24 11:27 UTC, how759 commented
___
*[lib/database.cc, line 97 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LnvkVEnEcmfo_07dpaQ:-LoPfWAh97xzVMpZJJDT:b-896fjx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/66c6b4fbef449eafc50450fd19a141669d6776d2/lib/database.cc#L97)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-09-25 10:15 UTC, ldorau reviewed
> Reviewed 3 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @how759, @igchor, and @lukaszstolarczuk)

___
*[lib/database.js, line 121 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lpbt_Gm8jHIU95YFO_R:-Lpbt_Gm8jHIU95YFO_S:br6d7dc) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/274dba76c7851d0688be939bfd457c2029807f41/lib/database.js#L121)):*
> ```JavaScript
> 
> module.exports = db;
> module.exports.constants = pmemkv.constants;
> ```

please add a new line at the end of the file


<!-- Sent from Reviewable.io -->

2019-09-25 10:50 UTC, how759 commented
___
*[lib/database.js, line 121 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lpbt_Gm8jHIU95YFO_R:-Lpc1noD8qcdWqOglg5Z:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/274dba76c7851d0688be939bfd457c2029807f41/lib/database.js#L121)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

please add a new line at the end of the file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-25 11:48 UTC, szyrom reviewed
please edit example (examples/basic_example.js) to start using JSON object instead of string and use catching exceptions

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-:-LpcEmDg-yMgJJLe98lV:bxyfzwd)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @igchor, @ldorau, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2019-09-25 11:51 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2019-09-25 13:05 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @how759, @igchor, and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 44 at r6](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpcWOup4w8b-NMrq9Uz:-LpcWOup4w8b-NMrq9V-:bgqyifk) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ffab3250077327770c5ff44776da7ce82beff789/utils/docker/images/prepare-pmemkv.sh#L44)):*
> ```Shell
> 
> # commit: Merge pull request #445 from ldorau/Add-testing-python-bindings-on-Travis; 24.09.2019
> current_pmemkv_version="99585189eba2e0a4d3e70aa17055557c0ab96789"
> ```

Please rebase on the current master - this change will not be needed and your Travis builds will be faster (the Docker image will not be rebuilt)


<!-- Sent from Reviewable.io -->

2019-09-26 05:33 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2019-09-26 08:23 UTC, igchor requested changes
> Reviewed 4 of 5 files at r4, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 5 unresolved discussions (waiting on @how759 and @lukaszstolarczuk)

___
*[lib/database.cc, line 258 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpgeO-j3bjR96IqESa3:-LpgeO-j3bjR96IqESa4:b-5fssp3) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/lib/database.cc#L258)):*
> ```cpp
>     std::string key2 = info[1].As<Napi::String>().Utf8Value();
>     Napi::Function cb = info[2].As<Napi::Function>();
>     this->_db.get_between(key1, key2, [&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
> ```

 Please add error handling with exceptions also here (and for other functions like get_keys, get_above, etc - they also return status, It was just not checked in nodejs yet). Here, just check if status != OK.
___
*[lib/database.cc, line 268 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpgdvB16ekVoVQYlcoR:-LpgdvB24atHqiNkgiV4:b-5j9pf4) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/lib/database.cc#L268)):*
> ```cpp
>     Napi::Env env = info.Env();
>     std::string key = info[0].As<Napi::String>().Utf8Value();
>     return Napi::Boolean::New(env, (_db.exists(key) == pmem::kv::status::OK));
> ```

Please add error handling with exception also here.

In this place the correct logic would be:

```
if (status != status::OK && status != status::NOT_FOUND) //throw exception
else return status
```


<!-- Sent from Reviewable.io -->

2019-09-26 16:24 UTC, lukaszstolarczuk reviewed
as for commits in this PR:

- the one "update pmemkv version in travis" (a7fb0a) seems unnecessary
- "add new line at the end of file" (a42c25) could be squashed (with "use errormsg() and pmem::kv::status to handle error", I believe)
- "update example" (11ee75) contains some Merge conflict messages - please remove them

rest of commits seems good and well divided for each functionality delivered.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-:-LpiN6Q93hb6XAg61w1K:bghvai3)* status: all files reviewed, 5 unresolved discussions (waiting on @how759 and @lukaszstolarczuk)

___
*[test/database_spec.js, line 215 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpiMGug1M7oCWKAr9G_:-LpiMGug1M7oCWKAr9Ga:bwybzuk) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/test/database_spec.js#L215)):*
> ```JavaScript
>             // when empty config do not cause a segmentFault in pmemkv
>             expect(e.message).to.equal("invalid config object");
>             
> ```

please remove these unnecessary whitespaces 


<!-- Sent from Reviewable.io -->

2019-09-27 06:36 UTC, how759 commented
___
*[lib/database.cc, line 268 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpgdvB16ekVoVQYlcoR:-LplQjDT2DCMtA1BElEm:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/lib/database.cc#L268)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add error handling with exception also here.

In this place the correct logic would be:

```
if (status != status::OK && status != status::NOT_FOUND) //throw exception
else return status
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-27 06:51 UTC, how759 commented
___
*[lib/database.cc, line 258 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpgeO-j3bjR96IqESa3:-LplU9mb9NTCpZuaALB0:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/lib/database.cc#L258)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

 Please add error handling with exceptions also here (and for other functions like get_keys, get_above, etc - they also return status, It was just not checked in nodejs yet). Here, just check if status != OK.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-27 06:52 UTC, how759 commented
___
*[test/database_spec.js, line 215 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpiMGug1M7oCWKAr9G_:-LplUVmS-cg6WHSKKugg:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/test/database_spec.js#L215)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please remove these unnecessary whitespaces 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-27 09:07 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @how759, @igchor, and @lukaszstolarczuk)

___
*[lib/database.cc, line 94 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LplwRnO9clyxAQrB6GG:-LplwRnO9clyxAQrB6GH:b9bd882) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/lib/database.cc#L94)):*
> ```
> XXX
> ```
As segfault issue was fixed in pmemkv, please update according to comment

https://github.com/pmem/pmemkv/commit/204b3b15e1f5d51638572797ced5fc32903f4288
___
*[test/database_spec.js, line 211 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpluJAc2141OP_mJ_7-:-Lpltt7X7YsElXPi9sQ9:b93y6sm) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/test/database_spec.js#L211)):*
> ```
> hen empty config do not cause a segmentFault in pmemkv
> ```
As segfault issue was fixed in pmemkv, please update according to comment

https://github.com/pmem/pmemkv/commit/204b3b15e1f5d51638572797ced5fc32903f4288


<!-- Sent from Reviewable.io -->

2019-09-29 05:59 UTC, how759 commented
___
*[lib/database.cc, line 94 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LplwRnO9clyxAQrB6GG:-LpvaZYPALdiGr_r5miG:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/lib/database.cc#L94)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

> ```
> XXX
> ```
As segfault issue was fixed in pmemkv, please update according to comment

https://github.com/pmem/pmemkv/commit/204b3b15e1f5d51638572797ced5fc32903f4288
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-29 05:59 UTC, how759 commented
___
*[test/database_spec.js, line 211 at r8](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-LpluJAc2141OP_mJ_7-:-LpvaalG-Fs4DknKvjJ0:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/11ee7532e36e9612eb4a6cbed33f60847afd7e7f/test/database_spec.js#L211)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

> ```
> hen empty config do not cause a segmentFault in pmemkv
> ```
As segfault issue was fixed in pmemkv, please update according to comment

https://github.com/pmem/pmemkv/commit/204b3b15e1f5d51638572797ced5fc32903f4288
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-30 08:49 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @how759, @igchor, @karczex, @ldorau, and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 43 at r9](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lq0Jk3zDC50MMRflr-0:-Lq0Jk3zDC50MMRflr-1:b-8zjgi1) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/a3d5cc02b16919773ea490a4a5f71b8d7752f831/utils/docker/images/prepare-pmemkv.sh#L43)):*
> ```Shell
> # stable_pmemkv_version="0.8"
> 
> # Merge pull request #454 from lukaszstolarczuk/use-correct-memkind-allocator-namespace, 27.09.2019
> ```

This update is unnecessary - it is not required by NodeJS.

The Travis build fails now, because this update requires libpmemobj-cpp also is updated.


<!-- Sent from Reviewable.io -->

2019-09-30 08:49 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @how759, @igchor, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2019-09-30 08:49 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @how759, @igchor, @karczex, and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 44 at r9](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lq0M6KZ-MFfjOaPHSH6:-Lq0M6KZ-MFfjOaPHSH7:b-8zjgi1) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/a3d5cc02b16919773ea490a4a5f71b8d7752f831/utils/docker/images/prepare-pmemkv.sh#L44)):*
> ```Shell
> 
> # Merge pull request #454 from lukaszstolarczuk/use-correct-memkind-allocator-namespace, 27.09.2019
> current_pmemkv_version="2f087b7e63a6f520474d795dbd8919ec86bf3c8d"
> ```

This update is unnecessary - it is not required by NodeJS.

The Travis build fails now, because this update requires libpmemobj-cpp also is updated.


<!-- Sent from Reviewable.io -->

2019-09-30 10:45 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r7, 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 8 unresolved discussions (waiting on @how759, @igchor, @karczex, and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 44 at r9](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lq0M6KZ-MFfjOaPHSH6:-Lq0lXq68mIUvZgUwnvB:bmj68g3) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/a3d5cc02b16919773ea490a4a5f71b8d7752f831/utils/docker/images/prepare-pmemkv.sh#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This update is unnecessary - it is not required by NodeJS.

The Travis build fails now, because this update requires libpmemobj-cpp also is updated.
</blockquote></details>

So this change should be removed


<!-- Sent from Reviewable.io -->

2019-09-30 12:51 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-:-Lq1DI3g2YRkox71rexv:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @how759, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2019-09-30 12:55 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 6 unresolved discussions (waiting on @how759, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2019-09-30 12:56 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 6 unresolved discussions (waiting on @how759, @karczex, and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 44 at r9](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lq0M6KZ-MFfjOaPHSH6:-Lq1EO0zECYydujBIHih:b-q348tt) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/a3d5cc02b16919773ea490a4a5f71b8d7752f831/utils/docker/images/prepare-pmemkv.sh#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So this change should be removed
</blockquote></details>

This change should be removed at all, not only reverted.


<!-- Sent from Reviewable.io -->

2019-09-30 12:58 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 44 at r9](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-Lq0M6KZ-MFfjOaPHSH6:-Lq1ElmrBgqcMm6-ss8E:b-ljq0ep) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/a3d5cc02b16919773ea490a4a5f71b8d7752f831/utils/docker/images/prepare-pmemkv.sh#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This change should be removed at all, not only reverted.
</blockquote></details>

Excuse me, my mistake. It is OK now.


<!-- Sent from Reviewable.io -->

2019-09-30 13:09 UTC, ldorau reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30#-:-Lq1HVWsCUFT92FzJgv-:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2019-09-30 13:44 UTC, ldorau commented
@igchor @lukaszstolarczuk @szyrom This PR requires https://github.com/pmem/pmemkv-nodejs/pull/37 to be merged before to make the Travis build pass.

2019-09-30 19:46 UTC, szyrom commented
@igchor @lukaszstolarczuk @karczex ?

2019-09-30 19:47 UTC, szyrom approved these changes

2019-10-01 11:01 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 5 files at r4, 1 of 1 files at r6, 1 of 2 files at r7, 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/30)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2019-10-01 11:23 UTC, closed without merging