support Buffer as arguments
pmem/pmemkv-nodejs pull request #49
Opened 2019-11-21 02:33 UTC by how759

support Node.js Buffer as arguments
    db.put(key_buf);
    db.get(key_buf); // return a Buffer
constructing a Buffer is faster than constructing a JS String in C++ layer

2019-11-29 14:44 UTC, igchor requested changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @how759)

___
*[binding.gyp, line 17 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYUJX8yeX89Nt_1El:-LurYUJX8yeX89Nt_1Em:b-9oyvcv) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/binding.gyp#L17)):*
> ```Python
>        ],
>        'cflags_cc!': [ '-fno-rtti'],
>        'cflags_cc': ['-fexceptions  -std=c++17']
> ```

why c++17 is needed? You can use pmem::kv::string_view
___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LurYYmM4_RK7wZgvTb5:bb37r1p) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
> ```objc
>     Napi::Value get_between(const Napi::CallbackInfo& info);
>     Napi::Value exists(const Napi::CallbackInfo& info);
>     Napi::Value get(const Napi::CallbackInfo& info);
> ```

why not also `get_as_buffer`
___
*[lib/database.js, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurbXE8DAtaIQ3Hi5Eg:-LurbXE8DAtaIQ3Hi5Eh:bujhez2) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.js#L56)):*
> ```JavaScript
> 	 * @constructor
> 	 * @throws {Error} on any failure.
> 	 * @param {string|Buffer} engine Name of the engine to work with.
> ```

From what I see there is no support for Buffer in pmemkv.db(engine, config)


<!-- Sent from Reviewable.io -->

2019-12-02 02:17 UTC, how759 commented
___
*[lib/database.js, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurbXE8DAtaIQ3Hi5Eg:-Lv3OHVNCZjXoaV4FP52:b-hfpv0l) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.js#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

From what I see there is no support for Buffer in pmemkv.db(engine, config)
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2019-12-02 02:17 UTC, how759 commented
___
*[binding.gyp, line 17 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYUJX8yeX89Nt_1El:-Lv3OQneAGW7VGyoUZu8:bb7f2mf) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/binding.gyp#L17)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why c++17 is needed? You can use pmem::kv::string_view
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2019-12-02 02:17 UTC, how759 commented
___
*[lib/database.js, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurbXE8DAtaIQ3Hi5Eg:-Lv3OOim7d9qHtPImFmR:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.js#L56)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-02 02:19 UTC, how759 commented
___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-Lv3OapF4F8x9yttULBo:b7us2u3) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why not also `get_as_buffer`
</blockquote></details>

The current design is:
get("string") return a string
get(Buffer) return  a Buffer


<!-- Sent from Reviewable.io -->

2019-12-11 11:28 UTC, igchor reviewed
Hi, sorry for replying just now but we had some discussion in the team about how to best expose binary (direct) interface for the data. In approach taken by this PR it's possible to mix binary and string keys - it can be problematic for defining order of keys (user would have to guarantee that all keys are either binary or strings to have some meaningful results). 

I think the best way to expose this would be to have to separate db classes (`db` and `db_buffer` or something like that). One would only accept keys as strings, and the second one would only accept binary data (and throw an exception for wrong type?). Type of the data can be both binary and string for both classes (so we would have `get_all `and `get_all_as_buffer`, etc. for both classes).

My argument behind this solution is also that currently, in pmemkv C/C++ we treat all data as bytes (including UTF-8 encoded strings we get from NodeJS). This means that we will sort those strings looking at bytes value (and not taking locale for account for example). If we split this to two classes, we can extend pmemkv C/C++ API to tell what type is the key and use that information for sorting.

Does that sound reasonable?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-:-Lvofo2DCZfAgHFHu3tK:b1fwo5u)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2019-12-13 08:30 UTC, how759 commented
> best expose binary (direct) interface for the data. In approach taken by this PR it's possible to mix binary and stri
Sorry that I don't quite understand the idea in the second paragraph. Do you means that `db` and `db_buffer` can accept both string and buffer inputs, but convert them either to string or buffer before passing it to C/C++? 

Besides, you also mention that this solution is currently, do you means that in the future pmemkv would support storing stringy and and binary key in separate ways?





<!-- Sent from Reviewable.io -->

2019-12-13 12:21 UTC, igchor requested changes
My idea was to accept only strings as keys for db class and only buffers as keys for db_buffer and throw error for wrong types. E.g we would not check what is the type of the key, if user provides wrong type - for example buffer for db class it will fail. Note that this is only for keys - for values I think we should be able to store both strings and buffers in both db and db_buffer. We could have methods:

```
class db {
   get(key) // returns string (key must be string)
   get_as_buffer(key, cb) // calls provided callback with buffer (key must be string)

   get_all(cb) // calls callback for all elements with key as string and value as string
   get_all_as_buffer(cb) // calls callback for all element with key as string and value as buffer

   get_above(key, cb) // calls callback for all elements with proper key with key as string and value as string
   get_above(key, cb) // calls callback for all elements with proper key with key as string and value as buffer

   put() // key is always treated as string and value can be either string or buffer
}

class db_buffer {
   get(key) // returns string (key must be buffer)
   get_as_buffer(key, cb) // calls provided callback with buffer (key must be buffer)

   get_all(cb) // calls callback for all elements with key as buffer and value as string
   get_all_as_buffer(cb) // calls callback for all element with key as buffer and value as buffer

   get_above(key, cb) // calls callback for all elements with proper key with key as buffer and value as string
   get_above(key, cb) // calls callback for all elements with proper key with key as buffer and value as buffer

   put(key, value) // key is always treated as buffer and value can be either string or buffer
}
```

And the answer for the second question is: yes - we want to support binary keys and string keys differently (for example take locale into consideration when comparing string).

Please also see my answer to one of the comment as to why we should not return buffer from get() but rather call callback with that buffer.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-:-Lvz7C4l3FNkKXf8JPc6:b-4w5efn)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @how759 and @igchor)

___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LvzBGrE4DoKu7TaaDCm:b-fk52nu) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

The current design is:
get("string") return a string
get(Buffer) return  a Buffer
</blockquote></details>

Actually returning a callback could be dangerous. For string there is no problem because we make a copy, but buffer points directly to the data in out db, right? If you have another thread which removes element with this key, your buffer now points to garbage.

The interface with buffers should use callbacks (like range query API) : get_as_buffer(key, cb). Inside pmemkv we are taking locks (for  engines which support concurrent access) for the duration of callback so we can guarantee that the element which is pointed by the buffer is not removed.


<!-- Sent from Reviewable.io -->

2019-12-13 12:22 UTC, igchor reviewed
edit: In the code snippet above the second get_above() method in both classes should be named get_above_as_buffer()

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-:-LvzCIfO83J5Sit1QOiP:b-lnmqod)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @how759 and @igchor)



<!-- Sent from Reviewable.io -->

2019-12-18 09:14 UTC, how759 commented
___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LwNDGXkBbkk_xLGNH0W:bvuy1sw) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually returning a callback could be dangerous. For string there is no problem because we make a copy, but buffer points directly to the data in out db, right? If you have another thread which removes element with this key, your buffer now points to garbage.

The interface with buffers should use callbacks (like range query API) : get_as_buffer(key, cb). Inside pmemkv we are taking locks (for  engines which support concurrent access) for the duration of callback so we can guarantee that the element which is pointed by the buffer is not removed.
</blockquote></details>

The current buffer is also constructed in a copy way. 
`Napi::Buffer<char>::Copy()`

I think it might not be secure to allow user to directly access the data in db. If we have to, we may need to implement a "read-only" buffer with "bound-check". 


<!-- Sent from Reviewable.io -->

2019-12-18 11:21 UTC, how759 commented
Thanks for the explanation, I get your point now. I think it make sense to split the db to different types according to keys' types.  For values' types, please refer to my answer below.





<!-- Sent from Reviewable.io -->

2019-12-23 09:18 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @how759 and @igchor)

___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LwlzSi-3LOFF4MOt9Be:b-mbqe74) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

The current buffer is also constructed in a copy way. 
`Napi::Buffer<char>::Copy()`

I think it might not be secure to allow user to directly access the data in db. If we have to, we may need to implement a "read-only" buffer with "bound-check". 

</blockquote></details>

I would say that the main benefit of pmemkv is that you can have direct access (currently read-only). This is especially important for C/C++ where it's natural to work with binary data. I think that we should also expose this direct, read-only access in nodejs and other bindings as well. There are several use cases for that:
- you could have gigabytes of data as one value and you may want to read only part of it.
- you could store terabytes of data in pmemkv and if you dont have direct access (alway copy) then for large values you could run out of main memory

I'm not sure how it looks in nodeJS but for example In Python, there are libraries (like numpy) which can work on memory views (which give direct read-only access to  the data). 


<!-- Sent from Reviewable.io -->

2019-12-23 09:19 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @how759 and @igchor)

___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-Lwm2EFV2Z5Dqp1SYKkA:bdjjy7a) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would say that the main benefit of pmemkv is that you can have direct access (currently read-only). This is especially important for C/C++ where it's natural to work with binary data. I think that we should also expose this direct, read-only access in nodejs and other bindings as well. There are several use cases for that:
- you could have gigabytes of data as one value and you may want to read only part of it.
- you could store terabytes of data in pmemkv and if you dont have direct access (alway copy) then for large values you could run out of main memory

I'm not sure how it looks in nodeJS but for example In Python, there are libraries (like numpy) which can work on memory views (which give direct read-only access to  the data). 
</blockquote></details>

I think the bound-checking you proposed would be a good solution


<!-- Sent from Reviewable.io -->

2019-12-24 08:03 UTC, how759 reviewed
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LwqtvVpAx6DYsU9JqwG:b98syfu) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think the bound-checking you proposed would be a good solution
</blockquote></details>

Currently Node.js do not support “read-only” and "bound-checking" property for Buffer type. I think we can use a proxy-based solution to implement a BufferView type to access the binary data.


<!-- Sent from Reviewable.io -->

2019-12-24 08:14 UTC, how759 commented
___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LwqxeAT78l-KkB5Q1wr:bq1z15j) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

Currently Node.js do not support “read-only” and "bound-checking" property for Buffer type. I think we can use a proxy-based solution to implement a BufferView type to access the binary data.
</blockquote></details>

The effect of out-of-bound access to native Buffer is that getting returns undefined and setting does nothing. We may need to throw an error in this circumstance.


<!-- Sent from Reviewable.io -->

2019-12-24 10:04 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @how759)

___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LwrM-DjBwFPLnl4L1IJ:b-1tge78) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

The effect of out-of-bound access to native Buffer is that getting returns undefined and setting does nothing. We may need to throw an error in this circumstance.
</blockquote></details>

Yes, that sounds reasonable. So, just to make sure I get it right - you suggest to implement our own type (with exceptions on out-of-bound access) on top of Buffer type? 


<!-- Sent from Reviewable.io -->

2019-12-24 10:06 UTC, how759 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[lib/database.h, line 64 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-LurYYmL77Ea9UTIL_CP:-LwrMetd65LKlQmAqEvf:bf1qajp) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/5021b571c30f8cd9fb239cb5bb329632ade6d251/lib/database.h#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, that sounds reasonable. So, just to make sure I get it right - you suggest to implement our own type (with exceptions on out-of-bound access) on top of Buffer type? 
</blockquote></details>

Yes. Also with "read-only" property.


<!-- Sent from Reviewable.io -->

2020-01-15 13:30 UTC, szyrom commented
@how759 are you able to implement it?

2020-01-16 05:44 UTC, how759 commented
yes, I will update in recent days. Sorry about the delay due to the vocations.





<!-- Sent from Reviewable.io -->

2020-01-21 13:42 UTC, how759 commented
@szyrom Please review

2020-02-03 11:24 UTC, igchor requested changes
> Reviewed 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @how759)

___
*[lib/database.cc, line 51 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9foChB6pavN8Z0UvI:-M-9foCi7lZ_1AvFsrvI:bjx229l) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.cc#L51)):*
> ```cpp
>     }
> 
> #define NAPI_CREATE_STRING(env, view) Napi::String::New(env, view.data(), view.size())
> ```

Does it have to be a macro? Could you change it to a function?
___
*[lib/database.js, line 48 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9icN0CMTCbHK3PYtH:-M-9icN0CMTCbHK3PYtI:b8tbzcd) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L48)):*
> ```JavaScript
> const immutable_buffer_proxy_handler = {
> 	set(target, prop, value){
> 		if (isNaN(prop)) {
> ```

why we check for `isNaN` here? Doe it mean that we can do `buffer = ...` but not `buffer.some_prop = ... ` ?
___
*[lib/database.js, line 53 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9ji5iDQD98ROygLlV:-M-9ji5iDQD98ROygLlW:b-v2z1u7) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L53)):*
> ```JavaScript
> 	},
> 	get(target, prop){
> 		if (typeof(target[prop]) == 'function') return target[prop].bind(target);
> ```

shouldn't we check for out-of-bounds access here (or is it handled by buffer/string)?
___
*[lib/database.js, line 70 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9l3BCCWa9sD42auQR:-M-9l3BCCWa9sD42auQS:b-6ulskd) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L70)):*
> ```JavaScript
> 	 * @param {string} engine Name of the engine to work with.
> 	 * @param {object} config JSON like config with parameters specified for the engine.
> 	 * @param {string} key_type Type of the key. Should be either "String" or "Buffer"
> ```

Please add information that when a database is created with key of certain type it should NOT be reopened later using different key type. For now, there is no support in pmemkv for enforcing that but we will add that in future (we will store info whether key is string or buffer and refuse to open pool when types are incompatible).


<!-- Sent from Reviewable.io -->

2020-02-03 11:25 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @how759)

___
*[lib/database.js, line 435 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9n0Qo9W_DLlIMwfml:-M-9n0Qo9W_DLlIMwfmm:b-n0gd1h) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L435)):*
> ```JavaScript
> 	 *	env.Undefined() if not found, or empty Value() if error.
> 	 */
> 	get_as_buffer(key) {
> ```

I dont' think we should expose get_as_buffer function - this will not be safe for multithreaded engines


<!-- Sent from Reviewable.io -->

2020-02-03 11:27 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @how759)

___
*[lib/database.js, line 288 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9nRtE0dVme4lZZDVC:-M-9nRtE0dVme4lZZDVD:b-l8b1va) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L288)):*
> ```JavaScript
> 	 * @throws {Error} on any failure.
> 	 * @param {string|Buffer} key - sets the lower bound for querying.
> 	 * @param {Function} callback - function to be called for each returned element.
> ```

shouldn't we add some info about what parameter this callback should take?


<!-- Sent from Reviewable.io -->

2020-02-05 06:45 UTC, how759 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @how759 and @igchor)

___
*[lib/database.cc, line 51 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9foChB6pavN8Z0UvI:-M-IxdKCDh1H_WNeE4lO:bfw8rka) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.cc#L51)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Does it have to be a macro? Could you change it to a function?
</blockquote></details>

ok, will do.
___
*[lib/database.js, line 48 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9icN0CMTCbHK3PYtH:-M-J-NQv0JdOKk-76GqD:b-tmcgk6) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L48)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why we check for `isNaN` here? Doe it mean that we can do `buffer = ...` but not `buffer.some_prop = ... ` ?
</blockquote></details>

The proxy here would trap all kinds of the property access including `buffer[0]` and `buffer.some_prop`.  The `immutable_buffer` take no action on setting `buffer[0]` but keep the native way on setting `buffer.some_prop` 
___
*[lib/database.js, line 53 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9ji5iDQD98ROygLlV:-M-J14AdBEavD28UCvnN:bt3f94e) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't we check for out-of-bounds access here (or is it handled by buffer/string)?
</blockquote></details>

In node.js, the native `Buffer` type will do the implicit out-of-bound check. When getting `buffer[buffer.length + 1]`, it will return `undefined`. 
___
*[lib/database.js, line 70 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9l3BCCWa9sD42auQR:-M-J2aq58XSXwIN7EE6Y:b-e66547) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L70)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add information that when a database is created with key of certain type it should NOT be reopened later using different key type. For now, there is no support in pmemkv for enforcing that but we will add that in future (we will store info whether key is string or buffer and refuse to open pool when types are incompatible).
</blockquote></details>

working, will do
___
*[lib/database.js, line 288 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9nRtE0dVme4lZZDVC:-M-J2wpW6UnnuuhpbTEg:b-e66547) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L288)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't we add some info about what parameter this callback should take?
</blockquote></details>

working, will do
___
*[lib/database.js, line 435 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9n0Qo9W_DLlIMwfml:-M-J3VqDE6I9tI4vLyWb:b-lb2vhf) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L435)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I dont' think we should expose get_as_buffer function - this will not be safe for multithreaded engines
</blockquote></details>

If we do not expose this function, how do we return the values as buffer?


<!-- Sent from Reviewable.io -->

2020-02-06 14:26 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @how759 and @igchor)

___
*[lib/database.js, line 435 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9n0Qo9W_DLlIMwfml:-M-PsWdjCQ7yKpCsyzQh:b-emoghv) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L435)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

If we do not expose this function, how do we return the values as buffer?
</blockquote></details>

We can implement it the same way as for get_all etc. - get() can take callback to be called on that one value. 
If you want to use the value outside of the callback you should copy it to your own buffer (btw, could you extend our example https://github.com/pmem/pmemkv-nodejs/blob/master/examples/basic_example.js with usage of buffer?)


<!-- Sent from Reviewable.io -->

2020-02-10 11:59 UTC, how759 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[lib/database.js, line 70 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9l3BCCWa9sD42auQR:-M-ixaQj3tDGkyBtmmkT:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L70)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

working, will do
</blockquote></details>

Done.
___
*[lib/database.js, line 288 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9nRtE0dVme4lZZDVC:-M-ixb_PB67GB1Ht9c6T:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L288)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

working, will do
</blockquote></details>

Done.
___
*[lib/database.js, line 435 at r4](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-9n0Qo9W_DLlIMwfml:-M-ixcOxA_ncmw16pe3x:bs7wumx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/b4710f38cd80e9d0af47f68b48f135e3c12f44c2/lib/database.js#L435)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We can implement it the same way as for get_all etc. - get() can take callback to be called on that one value. 
If you want to use the value outside of the callback you should copy it to your own buffer (btw, could you extend our example https://github.com/pmem/pmemkv-nodejs/blob/master/examples/basic_example.js with usage of buffer?)
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2020-02-11 14:06 UTC, igchor requested changes
> Reviewed 1 of 4 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 2 unresolved discussions (waiting on @how759)

___
*[lib/database.cc, line 56 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-nkvze676P5gGlZOpx:-M-nkvze676P5gGlZOpy:bgoi2gv) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L56)):*
> ```cpp
> 
> Napi::Buffer<char> create_napi_buffer(Napi::Env env, pmem::kv::string_view view){
>     return Napi::Buffer<char>::New(env, const_cast<char*>(view.data()), view.size());
> ```

why you cast it to char*, cant we hust have Buffer<const char>?
___
*[test/database_spec.js, line 807 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-oZEOa5uVtvekmbM76:-M-oZEOa5uVtvekmbM77:b-1jt0vf) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L807)):*
> ```JavaScript
>         db.get_between(Buffer.from('B'), Buffer.from('A'), (k, v) => x += `${k.toString()},${v.toString()}|`);
>         expect(x).to.equal('');
> ```

Could you also add some test for buffer indexing/slicing? Something like:

```
db.put('key2', 'value2')
db.get_as_buffer('key2', (v) => {
    assert(v.slice(2,4).toString() === 'lu');
});
```

Also this could also be added to an example. Using this in such a way will not result in whole value being copied, right? (only 2 bytes - from 2nd to 4th will be copied) 


<!-- Sent from Reviewable.io -->

2020-02-11 14:40 UTC, KFilipek reviewed
> Reviewed 1 of 4 files at r4, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 33 unresolved discussions (waiting on @how759)

___
*[lib/database.cc, line 41 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ocdjdDgAy_ngVwpgD:-M-ocdjdDgAy_ngVwpgE:b-wknwoq) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L41)):*
> ```cpp
>         str_##output = input.As<Napi::String>().Utf8Value();\
>         output = pmem::kv::string_view(str_##output);\
>     }\
> ```

} else if [...]
___
*[lib/database.cc, line 45 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ociZ6CXZRq_IG77XT:-M-ociZ6CXZRq_IG77XU:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L45)):*
> ```cpp
>         Napi::Buffer<char> buffer = input.As<Napi::Buffer<char>>();\
>         output = pmem::kv::string_view(buffer.Data(), buffer.Length());\
>     }\
> ```

} else {
___
*[lib/database.cc, line 125 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ocrQW5GJe-pSzYBSX:-M-ocrQW5GJe-pSzYBSY:b-wknwoq) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L125)):*
> ```cpp
>     if (key_type.compare("String") == 0){
>         this->_key_type = KEY_TYPE_STRING;
>     }
> ```

} else if [...]
___
*[lib/database.cc, line 128 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ocuqK4mvixoKy6YXC:-M-ocuqK4mvixoKy6YXD:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L128)):*
> ```cpp
>     else if (key_type.compare("Buffer") == 0){
>         this->_key_type = KEY_TYPE_BUFFER;
>     }
> ```

} else {
___
*[lib/database.cc, line 188 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-odUHI5wweSGuiUh8r:-M-odUHI5wweSGuiUh8s:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L188)):*
> ```cpp
>             return 0;
>         });
>     }
> ```

} else {
___
*[lib/database.cc, line 209 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-odXMP8vnMcyr9DN1b:-M-odXMP8vnMcyr9DN1c:b-1t5lwt) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L209)):*
> ```cpp
>     Napi::Function cb = info[1].As<Napi::Function>();
>     pmem::kv::status status;
>     if (_key_type == KEY_TYPE_STRING){
> ```

space after parenthesis
___
*[lib/database.cc, line 214 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-odbz_C_qD6SoWqXKX:-M-odbzaCU8L-rY7jXxt:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L214)):*
> ```cpp
>             return 0;
>         });
>     }
> ```

} else {
___
*[lib/database.cc, line 240 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-odk5W3vncKEET-vq8:-M-odk5W3vncKEET-vq9:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L240)):*
> ```cpp
>             return 0;
>         });
>     }
> ```

} else {
___
*[lib/database.cc, line 266 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-of2APASnGl3xdJvjy:-M-of2APASnGl3xdJvjz:bdtgao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L266)):*
> ```cpp
>         status = this->_db.get_between(key1, key2, [&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>             cb.Call(env.Global(), {create_napi_string(env, key)});
>             return 0;
> ```

Why not Napi::Value();?
___
*[lib/database.cc, line 268 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-odnwRCkVIyIr5L2V0:-M-odnwRCkVIyIr5L2V1:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L268)):*
> ```cpp
>             return 0;
>         });
>     }
> ```

} else {
___
*[lib/database.cc, line 272 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-oea1c2RuqMqPrUn11:-M-oea1dCulPNBOlvowK:bdtgao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L272)):*
> ```cpp
>         status = this->_db.get_between(key1, key2, [&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>             cb.Call(env.Global(), {create_napi_buffer(env, key)});
>             return 0;
> ```

Why not Napi::Value();?
___
*[lib/database.cc, line 350 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ofERc-Qt-R2CalDKP:-M-ofERd3_9ErfKLuF_d:bdtgao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L350)):*
> ```cpp
>         status = this->_db.get_all([&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>             cb.Call(env.Global(), {create_napi_string(env, key), create_napi_string(env, value)});
>             return 0;
> ```

Why not Napi::Value();?
___
*[lib/database.cc, line 352 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ofGTm4AxAm5cLdiIc:-M-ofGTm4AxAm5cLdiId:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L352)):*
> ```cpp
>             return 0;
>         });
>     }
> ```

} else {
___
*[lib/database.cc, line 374 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-of66K0CmoNJz_t1rE:-M-of66K0CmoNJz_t1rF:bdtgao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L374)):*
> ```cpp
>         status = this->_db.get_all([&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>             cb.Call(env.Global(), {create_napi_string(env, key), create_napi_buffer(env, value)});
>             return 0;
> ```

Why not Napi::Value();?
___
*[lib/database.cc, line 380 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-of6wR2jDmbWGTgYfj:-M-of6wR2jDmbWGTgYfk:bdtgao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L380)):*
> ```cpp
>         status = this->_db.get_all([&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>             cb.Call(env.Global(), {create_napi_buffer(env, key), create_napi_buffer(env, value)});
>             return 0;
> ```

Why not Napi::Value();?
___
*[lib/database.cc, line 403 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ofcHW8JhhNDr0acN5:-M-ofcHW8JhhNDr0acN6:b-wjxh2c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L403)):*
> ```cpp
>             return 0;
>         });
>     }
> ```

} else {
___
*[lib/database.cc, line 407 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ofi5pBHcG47WeeqSJ:-M-ofi5pBHcG47WeeqSK:bdtgao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L407)):*
> ```cpp
>         status = this->_db.get_above(key, [&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>             cb.Call(env.Global(), {create_napi_buffer(env, key), create_napi_string(env, value)});
>             return 0;
> ```

Why not Napi::Value();?
___
*[lib/database.cc, line 427 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ofjZQ9TWIdai1guap:-M-ofjZQ9TWIdai1guaq:bdtgao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L427)):*
> ```cpp
>         status = this->_db.get_above(key, [&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>             cb.Call(env.Global(), {create_napi_string(env, key), create_napi_buffer(env, value)});
>             return 0;
> ```

Why not Napi::Value(); [...]

2020-02-12 07:57 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 34 unresolved discussions (waiting on @how759)

___
*[lib/database.cc, line 36 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-sNOIO1Z04DG0NKAHX:-M-sNOIPA42UNjEtNwrg:b-pxjyh8) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L36)):*
> ```cpp
> #include <string>
> 
> #define GET_STRING_VIEW(input, output) \
> ```

Why is it macro instead of function? 


<!-- Sent from Reviewable.io -->

2020-02-12 09:00 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 34 unresolved discussions (waiting on @how759, @karczex, and @KFilipek)

___
*[lib/database.cc, line 36 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-sNOIO1Z04DG0NKAHX:-M-sb-dm2h4x5w0btQth:bgs72xk) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L36)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Why is it macro instead of function? 
</blockquote></details>

I would also prefer a function but I have no idea how to achieve the same result with a function, if you have any idea you can suggest something.
___
*[lib/database.cc, line 380 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-of6wR2jDmbWGTgYfj:-M-sbXGRCi2jidy3EUut:b-u2b3pb) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L380)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why not Napi::Value();?
</blockquote></details>

This is return value from a callback, not from a nodejs function.
___
*[lib/database.cc, line 576 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-og0Ff8eIAUvpPqBSX:-M-sbg1p-nmhayzyS4Gu:b-590pe8) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L576)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

} else if (
</blockquote></details>

Since we do not have any style checker currently for nodejs we should not change that now (this PR just follows the same convention which was used earlier). If we want to change the style we can do that but in a separate PR.


<!-- Sent from Reviewable.io -->

2020-02-12 11:51 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 4 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 42 unresolved discussions (waiting on @how759, @karczex, and @KFilipek)

___
*[lib/database.cc, line 601 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-su0cZEomYRd9GIZrB:-M-su0c_EsJYYiEra1N_:b-5s3c4k) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L601)):*
> ```cpp
>         e.ThrowAsJavaScriptException();
>     }
>     return Napi::Value();
> ```

in case of `status::NOT_FOUND` shouldn't this method return `env.Undefined` like in `db::get()` method?
___
*[lib/database.js, line 117 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-swF668h1hNMjPyS3g:-M-swF677HwltQ5B4eYa:b-hc38gz) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.js#L117)):*
> ```JavaScript
> 	 * @param {Function} callback - function to be called for every element stored in db.
> 	 *		It has only one param - key (for each returned element).
> 	 *		Type of the key is consistent with _key_type
> ```

put a dot '.' at the end of the sentence (a punctuation mark)

please fix here and in all other comments
___
*[lib/database.js, line 251 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-t77YRBxMcYIe7HZET:-M-t77YRBxMcYIe7HZEU:b-6alpnt) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.js#L251)):*
> ```JavaScript
> 	 * @throws {Error} on any failure.
> 	 * @param {Function} callback - function to be called for every element stored in db.
> 	 *		It has only two params - key and value (for each returned element).
> ```

"only" is redundant here

please remove in all descriptions, which contains "two params"
___
*[lib/database.js, line 267 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-t7t0i-tzakyHXUkop:-M-t7t0i-tzakyHXUkoq:bjn4tsr) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.js#L267)):*
> ```JavaScript
> 
> 	/**
> 	 * Executes function for every record stored in db.
> ```

please describe why these functions (with suffix `_as_buffer`) are different than `get_*`
___
*[test/database_spec.js, line 318 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tA-r_3O4RbM3-zacY:-M-tA-ra78Vo0FAgzY-R:b-pta5yq) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L318)):*
> ```JavaScript
>         db.get_keys((k) => x += `<${k.toString()}>,`);
>         expect(x).to.equal('<1>,<2>,<记!>,');
>     });
> ```

missing `db.stop()`
___
*[test/database_spec.js, line 629 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tD2qDEcW5jdNUijb6:-M-tD2qEEglbmlesZPMz:bf1p94p) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L629)):*
> ```JavaScript
>         expect(x).to.equal('BB,5|BC,6|记!,RR|');
> ```

one redundant empty line
___
*[test/database_spec.js, line 659 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tDBn76xYUcHMQaNEP:-M-tDBn76xYUcHMQaNEQ:bf1p94p) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L659)):*
> ```JavaScript
>         expect(x).to.equal('BB,5|BC,6|记!,RR|');
> ```

one redundant empty line
___
*[test/database_spec.js, line 810 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tDzad1uvwdabsgqgP:-M-tDzad1uvwdabsgqgQ:b9y22x3) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L810)):*
> ```JavaScript
>         db.stop();
>     });
> ```

I can see only 2 tests using `*_as_buffer` methods - can you please add more tests (of course for both cases - using strings and buffers as parameter).


<!-- Sent from Reviewable.io -->

2020-02-12 12:26 UTC, KFilipek reviewed
> Reviewed 1 of 4 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 14 unresolved discussions (waiting on @how759, @igchor, and @karczex)

___
*[lib/database.cc, line 380 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-of6wR2jDmbWGTgYfj:-M-tLkO041OY1A0tbcc1:b-ds8dbr) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L380)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This is return value from a callback, not from a nodejs function.
</blockquote></details>

Oh, okey, I will retract related comments
___
*[lib/database.cc, line 576 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-og0Ff8eIAUvpPqBSX:-M-tM0L3BkNpv9rdDJ6d:bb74ce2) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L576)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Since we do not have any style checker currently for nodejs we should not change that now (this PR just follows the same convention which was used earlier). If we want to change the style we can do that but in a separate PR.
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2020-02-12 13:22 UTC, how759 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 14 unresolved discussions (waiting on @how759, @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[lib/database.cc, line 36 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-sNOIO1Z04DG0NKAHX:-M-tU-LkE49u8gUmt8pa:bgjpgnw) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L36)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would also prefer a function but I have no idea how to achieve the same result with a function, if you have any idea you can suggest something.
</blockquote></details>

We have to throw an error by `Napi::Error::New()` and then return. Using a function cannot tell outside function to return Napi::Value() directly.
___
*[lib/database.cc, line 41 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-ocdjdDgAy_ngVwpgD:-M-tX6W51w5CkvNftccv:btuuwd6) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L41)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

} else if [...]
</blockquote></details>

Do you have any format tools to do these formatting?
___
*[lib/database.cc, line 56 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-nkvze676P5gGlZOpx:-M-tRNK18RZnWf97Lcdt:bgmm2il) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why you cast it to char*, cant we hust have Buffer<const char>?
</blockquote></details>

The `Napi::Buffer<char>::New()` only accept char*, not const char*.  And this is why we implement a immutable_buffer to forbid users to write it
___
*[lib/database.cc, line 380 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-of6wR2jDmbWGTgYfj:-M-tXsMRAXQ36Di5Xg-M:b32wtd) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L380)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Oh, okey, I will retract related comments
</blockquote></details>

ok
___
*[lib/database.cc, line 601 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-su0cZEomYRd9GIZrB:-M-tY8MZ2u6PcOtdBYHD:by7izy7) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L601)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in case of `status::NOT_FOUND` shouldn't this method return `env.Undefined` like in `db::get()` method?
</blockquote></details>

`Napi::Value()` is equivalent to `env.Undefined()`. I'll update it to`env.Undefined` to avoid ambiguity
___
*[lib/database.js, line 117 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-swF668h1hNMjPyS3g:-M-tYuXlBv4iBe31fsx3:b32wtd) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.js#L117)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put a dot '.' at the end of the sentence (a punctuation mark)

please fix here and in all other comments
</blockquote></details>

ok
___
*[test/database_spec.js, line 807 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-oZEOa5uVtvekmbM76:-M-tZBn_BHFvxNev_AHc:bbywahw) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L807)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you also add some test for buffer indexing/slicing? Something like:

```
db.put('key2', 'value2')
db.get_as_buffer('key2', (v) => {
    assert(v.slice(2,4).toString() === 'lu');
});
```

Also this could also be added to an example. Using this in such a way will not result in whole value being copied, right? (only 2 bytes - from 2nd to 4th will be copied) 
</blockquote></details>

ok, will do
___
*[test/database_spec.js, line 810 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tDzad1uvwdabsgqgP:-M-tZDju-YWx4VBcd-a6:b32wtd) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L810)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I can see only 2 tests using `*_as_buffer` methods - can you please add more tests (of course for both cases - using strings and buffers as parameter).
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2020-02-12 13:27 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 13 unresolved discussions (waiting on @how759, @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[lib/database.cc, line 56 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-nkvze676P5gGlZOpx:-M-tZhWfAFORMOOGm0BG:blz9b3j) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L56)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

The `Napi::Buffer<char>::New()` only accept char*, not const char*.  And this is why we implement a immutable_buffer to forbid users to write it
</blockquote></details>

ok, couldn't we also have `Buffer<const char>` instead of `Buffer<char>` ?


<!-- Sent from Reviewable.io -->

2020-02-12 13:35 UTC, how759 commented
___
*[lib/database.cc, line 56 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-nkvze676P5gGlZOpx:-M-tagfE0c0_e4QXCDNy:b-dzxy18) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

ok, couldn't we also have `Buffer<const char>` instead of `Buffer<char>` ?
</blockquote></details>

No, the `Buffer<T>` would try to convert `T*` to `void*` internally. 


<!-- Sent from Reviewable.io -->

2020-02-13 07:22 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 17 unresolved discussions (waiting on @how759, @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[lib/database.cc, line 36 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-sNOIO1Z04DG0NKAHX:-M-xJImP10RdFzzewRd_:b-cxxn57) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L36)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

We have to throw an error by `Napi::Error::New()` and then return. Using a function cannot tell outside function to return Napi::Value() directly.
</blockquote></details>

Sound's reasonable. 
Please just  enclose it in do{} while(0)  

http://www.bruceblinn.com/linuxinfo/DoWhile.html
___
*[lib/database.cc, line 260 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xOrZY7VXx0dgMud5L:-M-xOrZY7VXx0dgMud5M:b-6uaxb4) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L260)):*
> ```cpp
>     GET_STRING_VIEW(info[0], key1);
>     pmem::kv::string_view key2;
>     GET_STRING_VIEW(info[1], key2)
> ```

Is lack of semicolon intentional here?  
___
*[lib/database.cc, line 331 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xPF8sDi9IKib2XiLo:-M-xPF8sDi9IKib2XiLp:b-6uaxb4) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L331)):*
> ```cpp
>     GET_STRING_VIEW(info[0], key1);
>     pmem::kv::string_view key2;
>     GET_STRING_VIEW(info[1], key2)
> ```

Is lack of semicolon intentional here?  
___
*[lib/database.cc, line 501 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xPc7rBthC0aXot-2c:-M-xPc7rBthC0aXot-2d:b-6uaxb4) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L501)):*
> ```cpp
>     GET_STRING_VIEW(info[0], key1);
>     pmem::kv::string_view key2;
>     GET_STRING_VIEW(info[1], key2)
> ```

Is lack of semicolon intentional here?  
___
*[lib/database.cc, line 529 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xPinf03ddlMfAfZrY:-M-xPinf03ddlMfAfZrZ:b-6uaxb4) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L529)):*
> ```cpp
>     GET_STRING_VIEW(info[0], key1);
>     pmem::kv::string_view key2;
>     GET_STRING_VIEW(info[1], key2)
> ```

Is lack of semicolon intentional here?  


<!-- Sent from Reviewable.io -->

2020-02-21 08:02 UTC, how759 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 2 of 5 files reviewed, 16 unresolved discussions (waiting on @how759, @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[lib/database.cc, line 36 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-sNOIO1Z04DG0NKAHX:-M0_pYqR5DwMVpNGJl8P:b-33ggmh) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L36)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Sound's reasonable. 
Please just  enclose it in do{} while(0)  

http://www.bruceblinn.com/linuxinfo/DoWhile.html
</blockquote></details>

Done, I have to move the definition of a `std::string` outside of the macro otherwise it would be released when exiting the do{}while(0)
___
*[lib/database.cc, line 260 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xOrZY7VXx0dgMud5L:-M0aJ-HT7JWqM_ct803a:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L260)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Is lack of semicolon intentional here?  
</blockquote></details>

Done.
___
*[lib/database.cc, line 331 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xPF8sDi9IKib2XiLo:-M0_q2dq90zlAI9pyRks:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L331)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Is lack of semicolon intentional here?  
</blockquote></details>

Done.
___
*[lib/database.cc, line 501 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xPc7rBthC0aXot-2c:-M0_q8Fq9VrSeqFbawPv:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L501)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Is lack of semicolon intentional here?  
</blockquote></details>

Done.
___
*[lib/database.cc, line 529 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-xPinf03ddlMfAfZrY:-M0_qA-UCvS8BEhRk1lo:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L529)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Is lack of semicolon intentional here?  
</blockquote></details>

Done.
___
*[lib/database.js, line 251 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-t77YRBxMcYIe7HZET:-M0_qDZP7SeeSwzC5oOs:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.js#L251)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"only" is redundant here

please remove in all descriptions, which contains "two params"
</blockquote></details>

Done.
___
*[lib/database.js, line 267 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-t7t0i-tzakyHXUkop:-M0aFKs10CWTqXEze9LJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.js#L267)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please describe why these functions (with suffix `_as_buffer`) are different than `get_*`
</blockquote></details>

Done.
___
*[test/database_spec.js, line 318 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tA-r_3O4RbM3-zacY:-M0aGJ-K1euZetvnxZIh:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L318)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing `db.stop()`
</blockquote></details>

Done.
___
*[test/database_spec.js, line 629 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tD2qDEcW5jdNUijb6:-M0aIbrLAUkvXF6PODSu:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L629)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

one redundant empty line
</blockquote></details>

Done.
___
*[test/database_spec.js, line 659 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tDBn76xYUcHMQaNEP:-M0aIdMB6wCCGjPXXafu:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L659)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

one redundant empty line
</blockquote></details>

Done.
___
*[test/database_spec.js, line 807 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-oZEOa5uVtvekmbM76:-M0ab53JBp9YK9XsOQFV:bxqah3r) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L807)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

ok, will do
</blockquote></details>

Tested in test case 'gets value as buffer'
___
*[test/database_spec.js, line 810 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-tDzad1uvwdabsgqgP:-M0aemCP9MfBXEjZjLw9:bnmitdg) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/test/database_spec.js#L810)):*
<details><summary><i>Previously, how759 wrote…</i></summary><blockquote>

ok
</blockquote></details>

Added in existing test cases


<!-- Sent from Reviewable.io -->

2020-02-24 10:22 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: 2 of 5 files reviewed, 10 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[lib/database.cc, line 576 at r5](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M-og0Ff8eIAUvpPqBSX:-M0qhuRa3iUU8pjoD3Zp:b9bq2i6) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fb2ba4abb694f63e95488d8c47719876743c66ee/lib/database.cc#L576)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

@kfilipek can you mark this a resolved?


<!-- Sent from Reviewable.io -->

2020-02-26 12:47 UTC, igchor reviewed
All looks good, could you just please squash "update annotation and use callback in get_as_buffer()" and "modified based on comments" commits with "specify key type on create db and use immutable buffer to access binary data"? Also please extend "update example" commit message to something like "Update example with get_as_buffer usage"

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-:-M10X2QQ4qzCkSzcfkx-:b-12sh6r)* status: 2 of 5 files reviewed, 10 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-02-27 10:43 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-:-M15EbE66ma80aCSNNDn:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-02-28 17:19 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49)* status: all files reviewed, 3 unresolved discussions (waiting on @how759 and @KFilipek)

___
*[lib/database.js, line 450 at r6](https://reviewable.io/reviews/pmem/pmemkv-nodejs/49#-M1Bn5Kf4dgOPBAWGJNW:-M1Bn5Kf4dgOPBAWGJNX:b35yo9m) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/d44b0c29ce016de9950d4efe632fa6fe7504f907/lib/database.js#L450)):*
> ```JavaScript
> 	/**
> 	 * Gets value of record with given *key*.
> 	 * The value of record is returned as buffer.
> ```

as string


<!-- Sent from Reviewable.io -->

2020-03-02 08:42 UTC, merged